version: '3.1'
services:
  postgres:
    image: postgres:10
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: souchen
        POSTGRES_PASSWORD: 123
        POSTGRES_DB: CHATapp
    volumes:
      - my_postgres_data:/var/lib/postgresql/data
    
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  my_postgres_data:
